services:
  - type: web
    name: trend-share
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr tesseract-ocr-rus && \
      pip install --upgrade pip && \
      pip install -r requirements.txt && \
      flask db stamp head && \
      flask db upgrade
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      # Добавьте ваши переменные окружения здесь, если необходимо
