services:
  - type: web
    name: trend-share
    env: python
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt && \
      flask db stamp head && \
      flask db upgrade
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    buildpacks:
      - https://github.com/heroku/heroku-buildpack-apt
      - heroku/python
    envVars:
      # Добавьте ваши переменные окружения здесь, если необходимо
