"""Добавлены поля real_price и deviation в модель UserPrediction

Revision ID: 872ec64f4402
Revises: 90f7a44fcc7e
Create Date: 2024-12-14 21:40:19.199594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872ec64f4402'
down_revision = '90f7a44fcc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('config_key_key', 'config', type_='unique')
    op.drop_column('config', 'id')
    op.create_unique_constraint('_instrument_date_uc', 'price_history', ['instrument_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_instrument_date_uc', 'price_history', type_='unique')
    op.add_column('config', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('config_key_key', 'config', ['key'])
    # ### end Alembic commands ###
